# This file is autogenerated from nimble.lock
# Do not edit manually
{ pkgs }:

{
  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha1 = "02bb3751ba9ddc3c17bfd89f2e41cb6bfb8fc0c9";
  };
  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "11e798b62b8e6beabe958e048e9e24c7e0f9ee63";
    sha1 = "7e068f119664cf47ad0cfb74ef4c56fb6b616523";
  };
  bearssl_pkey_decoder = pkgs.fetchgit {
    url = "https://github.com/vacp2p/bearssl_pkey_decoder";
    rev = "21dd3710df9345ed2ad8bf8f882761e07863b8e0";
    sha1 = "21b42e2e6ddca6c875d3fc50f36a5115abf51714";
  };
  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha1 = "a9c011f74bc9ed5c91103917b9f382b12e82a9e7";
  };
  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "b66168735d6f3841c5239c3169d3fe5fe98b1257";
    sha1 = "928e82cb8d2f554e8f10feb2349ee9c32fee3a8c";
  };
  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "ce27581a3e881f782f482cb66dc5b07a02bd615e";
    sha1 = "ee61e507b805ae1df7ec936f03f2d101b0d72383";
  };
  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b0f2fa32960ea532a184394b0f27be37bd80248b";
    sha1 = "fa35c1bb76a0a02a2379fe86eaae0957c7527cb8";
  };
  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha1 = "8b3115354104858a0ac9019356fb29720529c2bd";
  };
  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "e4d37dc1652d5c63afb89907efb5a5e812261797";
    sha1 = "d1678f50aa47d113b4e77d41eec2190830b523fa";
  };
  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha1 = "02febb20d088120b2836d3306cfa21f434f88f65";
  };
  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "c53852d9e24205b6363bba517fa8ee7bde823691";
    sha1 = "298bc5b6fe4e5aa9c3b7e2ebfa17191675020f10";
  };
  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "712f9937e46a9ba1949230e8e119d776aea1c6bb";
    sha1 = "03e96742e7148c38767c028c23a99cf316672f1c";
  };
  dnsclient = pkgs.fetchgit {
    url = "https://github.com/ba0f3/dnsclient.nim";
    rev = "23214235d4784d24aceed99bbfe153379ea557c8";
    sha1 = "65262c7e533ff49d6aca5539da4bc6c6ce132f40";
  };
  jwt = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-jwt.git";
    rev = "18f8378de52b241f321c1f9ea905456e89b95c6f";
    sha1 = "bcfd6fc9c5e10a52b87117219b7ab5c98136bc8e";
  };
  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "c71efff5fd1721362b3363dc7d0e2a4c0dbc6453";
    sha1 = "b98773348eda614ff6b252213dcd852fc9d68e89";
  };
  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha1 = "f72b90fe3f4da09efa482de4f8729e7ee4abea2f";
  };
  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "f3fe33462601ea34eb2e8e9c357c92e61f8d121b";
    sha1 = "407b39ad3e84ad794b76df8d63ecafb749af6f4f";
  };
  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "11d0cddfb0e711aa2a8c75d1892ae24a64c299fc";
    sha1 = "5cdac99d85d3c146d170e85064c88fb28f377842";
  };
  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "b526c4b436809aa1cfe650026d796cf7b8328b91";
    sha1 = "e6e50bd4a29cb473b070eb5359d87d8946d96075";
  };
  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "35ae76f1559e835c80f9c1a3943bf995d3dd9eb5";
    sha1 = "1cb5efa10cd389bc01d0707c242ae010c76a03cd";
  };
}
