# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "22c6a76ce015bc07e011562bdcfc51d9446c1e82";
    sha256 = "1cvdd7lfrpa6asmc39al3g4py5nqhpqmvypc36r5qyv7p5arc8a3";
    fetchSubmodules = true;
  };

  bearssl_pkey_decoder = pkgs.fetchgit {
    url = "https://github.com/vacp2p/bearssl_pkey_decoder";
    rev = "d34aa46bf9d0a3ffff810fbd3c4d2fa024eb9368";
    sha256 = "0200f7lf3x2hypwr2v9gms6qv7wj8m1phwd25025bfa1w9f2nkbg";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "1c91a4a2579123597df43bbdea70cc575957bdea";
    sha256 = "0vh26cdski46jaaqfxqz8pfzjxxnkr3znvyqdgn5m6q4xkbb1jqz";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "4382b18f04b3c43c8409bfcd6b62063773b2bbaa";
    sha256 = "0mx9g5m636h3sk5pllcpylk51brf7lx91izx3gc23k3ih3hrxyk2";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "50889cd16ec8771106cdd0eeea460039e8571e06";
    sha256 = "1hd4bhvw5lzwg924i8dif5mi61h0ayiplq38djvrdbfsjdhw2zvw";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b0f2fa32960ea532a184394b0f27be37bd80248b";
    sha256 = "0wip1fjx7ka39ck1g1xvmyarzq1p5dlngpqil6zff8k8z5skiz27";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha256 = "0i8sq51nqj8lshf6bfixaz9a7sq0ahsbvq3chkxdvv4khsqvam91";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "6ce5e5e2301ccbc04b09d27ff78741ff4d352b4d";
    sha256 = "1vbkr6i5yxhc2ai3b7rbglhmyc98f99x874fqdp6a152a6kqgwxy";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha256 = "1xx9fcfwgcaizq3s7i3s03mclz253r5j8va38l9ycl19fcbc96z9";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "f142cb2e8bd812dd002a6493b6082827bb248592";
    sha256 = "03msj4zdxraz4qx9cidb17g7v0asazxv91nng6xxbzjxz0qaqxw6";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "45f43a9ad8bd8bcf5903b42f365c1c879bd54240";
    sha256 = "1v1n59zfzznp97pvwgs9kf136bqmv4x2s2y9f24msspa7qv27w39";
    fetchSubmodules = true;
  };

  dnsclient = pkgs.fetchgit {
    url = "https://github.com/ba0f3/dnsclient.nim";
    rev = "23214235d4784d24aceed99bbfe153379ea557c8";
    sha256 = "03mf3lw5c0m5nq9ppa49nylrl8ibkv2zzlc0wyhqg7w09kz6hks6";
    fetchSubmodules = true;
  };

  jwt = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-jwt.git";
    rev = "057ec95eb5af0eea9c49bfe9025b3312c95dc5f2";
    sha256 = "1hnxsl5762fdn80hl4xxfdqrcgmxrrfck66js1iqaqfxc4m0fv63";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "e680f269fb01af2c34a2ba879ff281795a5258fe";
    sha256 = "1xw9f1gjsgqihdg7kdkbaq1wankgnx2vn9l3ihc6nqk2jzv5bvk5";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha256 = "1v4rz42lwcazs6isi3kmjylkisr84mh0kgmlqycx4i885dn3g0l4";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "00e4b7dfaa197cd120267aa897b33b0914166b45";
    sha256 = "0kfkcscafiz82amj7skn5hspqhs6ixdz09hy64cfhsxyd6mi48nq";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "a1296caf3ebb5f30f51a5feae7749a30df2824c2";
    sha256 = "02vxqy20g8012ks939ac25ksc25k727q84si0p2cmihy5bw1a3qm";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "46753f2b90365035bc0f75c6894e160c35880be1";
    sha256 = "1m7gm6h974ks0iypyq6cq6p6k8skl48mjpnfxms79yfn4s49qcvd";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "42c37b4172519566db016810eccfce8a02cc1cdf";
    sha256 = "1l5laqyvfbldiii1vrp1crx56lvbdn1xm5hbnl3mcihbn18lzvxg";
    fetchSubmodules = true;
  };

}
