# AUTOGENERATED from tests/nimble.lock
# Do not edit manually
{ pkgs }:

{
  libbacktrace = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-libbacktrace";
    rev = "af60500cb0383231065f1d6624beeeefa308d085";
    sha256 = "0gmdjb04qqj1hpm79apnbdlk150ns2w59ky5g511wzkacyv81ki3";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

}
