header:
  license:
    content:
      | 
      # SPDX-License-Identifier: Apache-2.0 OR MIT
      # Copyright (c) Status Research & Development GmbH 
  paths:
  - "**/*.nim"
  paths-ignore:
  - "examples/**"
  comment: on-failure