codecov:
  notify:
    require_ci_to_pass: true
    # must be the number of coverage report builds
    # notice that this number is for PRs;
    # like this we disabled notify on pure branches report
    # which is fine I guess
    after_n_builds: 28
comment:
  layout: "reach, diff, flags, files"
  after_n_builds: 28 # must be the number of coverage report builds
coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
        base: auto