site_name: nim-libp2p

repo_url: https://github.com/vacp2p/nim-libp2p
repo_name: vacp2p/nim-libp2p
site_url: https://vacp2p.github.io/nim-libp2p/docs
# Can't find a way to point the edit to the .nim instead
# of the .md
edit_uri: ''

docs_dir: examples

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  logo: https://libp2p.io/img/logo_small.png
  favicon: https://libp2p.io/img/logo_small.png
  name: material
  features:
    - navigation.instant
    - search.highlight
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Tutorials:
    - 'Introduction': index.md
    - 'Simple connection': tutorial_1_connect.md
    - 'Create a custom protocol': tutorial_2_customproto.md
    - 'Protobuf': tutorial_3_protobuf.md
    - 'GossipSub': tutorial_4_gossipsub.md
    - 'Discovery Manager': tutorial_5_discovery.md
    - 'Game': tutorial_6_game.md
    - 'Circuit Relay': circuitrelay.md
  - Reference: '/nim-libp2p/master/libp2p.html'
