{
 "title": "libp2p metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "peer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "peers (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "libp2p_pubsub_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "nbc_peers{instance=\"${instance}\"}",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbc_peers{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "open streams (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=\"${instance}\"}",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "message tx queuing delay (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(libp2p_mplex_qtime_bucket{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "message tx queue length (msgs) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(libp2p_mplex_qlen_bucket{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peer connections closed / second (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_mplex_qlenclose_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "reason: max queue length reached"
    }
   ]
  },
  { "title": "Gossipsub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Mesh health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_healthy_peers_topics{instance=\"${instance}\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "libp2p_gossipsub_low_peers_topics{instance=\"${instance}\"}",
     "legendFormat": "low"
    },
    {
     "expr": "libp2p_gossipsub_no_peers_topics{instance=\"${instance}\"}",
     "legendFormat": "no_peers"
    }
   ]
  },
  {
   "title": "gossipsub duplicates / second (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_duplicate_during_validation_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "duplicates during validation"
    },
    {
     "expr": "rate(libp2p_gossipsub_duplicate_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "duplicates received"
    },
    {
     "expr": "rate(libp2p_gossipsub_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "gossipsub duplicates received ratio (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_duplicate_total{instance=\"${instance}\"}[$__rate_interval]) / rate(libp2p_gossipsub_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "duplicates received ratio"
    }
   ]
  },
  {
   "title": "topic subscription (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_pubsub_topic_handlers{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "gossipsub iwant and mcache / second (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval]) - rate(libp2p_gossipsub_mcache_hit_sum{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "mcache miss"
    },
    {
     "expr": "rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "mcache hit"
    },
    {
     "expr": "rate(libp2p_pubsub_received_iwant_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "iwant received"
    }
   ]
  },
  {
   "title": "gossipsub mcache hit ratio (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_mcache_hit_sum{instance=\"${instance}\"}[$__rate_interval]) / rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "mcache hits"
    }
   ]
  },
  {
   "title": "gossipsub iwant, ihave: msgids / second (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_pubsub_broadcast_iwant_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "iwant msgids sent"
    },
    {
     "expr": "rate(libp2p_pubsub_received_iwant_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "iwant msgids received"
    },
    {
     "expr": "sum by (instance) (rate(libp2p_pubsub_broadcast_ihave_total{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "ihave cmds sent"
    },
    {
     "expr": "sum by (instance) (rate(libp2p_pubsub_received_ihave_total{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "ihave cmds received"
    }
   ]
  },
  {
   "title": "gossipsub bytes / second (${instance})",
   "type": "timeseries",
   "description": "Requires -d:libp2p_protobuf_metrics",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_pubsub_rpc_bytes_read_total{instance=\"${instance}\"}[$__rate_interval])"
    },
    {
     "expr": "rate(libp2p_pubsub_rpc_bytes_write_total{instance=\"${instance}\"}[$__rate_interval])"
    }
   ]
  }
 ]
}