{
 "title": "local nimlibp2p",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "LibP2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "libp2p_peers{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Libp2p Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "libp2p_open_streams", "legendFormat": "{{instance}}-{{type}}-{{dir}}" }
   ]
  },
  {
   "title": "libp2p traffic - In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "libp2p traffic - Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Nim GC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"simulation\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}-{{container_label_com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "libp2p unhealthy peers (d_low)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_low_peers_topics > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "libp2p healthy peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_healthy_peers_topics",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}