{
 "title": "libp2p metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "message tx queuing delay (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(libp2p_protocols_qtime_bucket{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "open streams (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=\"${instance}\"}",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "peers (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "libp2p_pubsub_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "nbc_peers{instance=\"${instance}\"}",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "message tx queue length (msgs) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(libp2p_protocols_qlen_bucket{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbc_peers{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "gossipsub duplicates / slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_duplicate_during_validation_total{instance=\"${instance}\"}[$__rate_interval]) * 12",
     "legendFormat": "duplicates during validation"
    },
    {
     "expr": "rate(libp2p_gossipsub_duplicate_total{instance=\"${instance}\"}[$__rate_interval]) * 12",
     "legendFormat": "duplicates received"
    },
    {
     "expr": "rate(libp2p_gossipsub_received_total{instance=\"${instance}\"}[$__rate_interval]) * 12",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "gossipsub duplicates received ratio (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_duplicate_total{instance=\"${instance}\"}[$__rate_interval]) / rate(libp2p_gossipsub_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "duplicates received ratio"
    }
   ]
  },
  {
   "title": "gossipsub iwant and mcache (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval]) - rate(libp2p_gossipsub_mcache_hit_sum{instance=\"${instance}\"}[$__rate_interval])) * 12",
     "legendFormat": "mcache miss"
    },
    {
     "expr": "rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval]) * 12",
     "legendFormat": "mcache hit"
    },
    {
     "expr": "rate(libp2p_pubsub_received_iwant_total{instance=\"${instance}\"}[$__rate_interval]) * 12",
     "legendFormat": "iwant received"
    }
   ]
  },
  {
   "title": "gossipsub mcache hit ratio (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_gossipsub_mcache_hit_sum{instance=\"${instance}\"}[$__rate_interval]) / rate(libp2p_gossipsub_mcache_hit_count{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "mcache hits"
    }
   ]
  },
  {
   "title": "topic subscription (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_pubsub_subscriptions_total{instance=\"${instance}\"}",
     "legendFormat": "topics"
    }
   ]
  }
 ]
}