name: Add Comment
description: "Add or update comment in the PR"

runs:
  using: "composite"
  steps:
    - name: Add/Update Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const marker = "${{ env.MARKER }}";
          const body = fs.readFileSync("${{ env.COMMENT_SUMMARY_PATH }}", 'utf8');
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const existing = comments.find(c => c.body && c.body.startsWith(marker));
          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }