#!/usr/bin/env bash
set -euo pipefail

LOCKFILE="nimble.lock"
DEPS_FILE="nix/deps.nix"

mkdir -p nix

command -v jq >/dev/null || { echo "jq required"; exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "nix-prefetch-git required"; exit 1; }

nimble lock
[ -f "$LOCKFILE" ] || { echo "nimble.lock not found"; exit 1; }

echo "[*] Generating $DEPS_FILE"

cat > "$DEPS_FILE" <<'EOF'
# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
EOF

jq -c '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
' "$LOCKFILE" | while read -r entry; do
  name=$(jq -r '.key' <<<"$entry")
  url=$(jq -r '.value.url' <<<"$entry")
  rev=$(jq -r '.value.vcsRevision' <<<"$entry")

  echo "[*] Prefetching $name"

  sha=$(nix-prefetch-git \
    --url "$url" \
    --rev "$rev" \
    --fetch-submodules \
    | jq -r '.sha256')

  cat >> "$DEPS_FILE" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
  };

EOF
done

cat >> "$DEPS_FILE" <<'EOF'
}
EOF

echo "[✓] deps.nix written"

