#!/usr/bin/env bash
set -euo pipefail

command -v jq >/dev/null || { echo "jq required"; exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "nix-prefetch-git required"; exit 1; }

generate_deps() {
  local lockfile="$1"
  local outfile="$2"

  echo "[*] Generating $outfile from $lockfile"

  if [ ! -f "$lockfile" ]; then
    echo "Lockfile not found: $lockfile"
    exit 1
  fi

  mkdir -p "$(dirname "$outfile")"

  cat > "$outfile" <<'EOF'
# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
EOF

  jq -c '
    .packages
    | to_entries[]
    | select(.value.downloadMethod == "git")
  ' "$lockfile" | while read -r entry; do
    name=$(jq -r '.key' <<<"$entry")
    url=$(jq -r '.value.url' <<<"$entry")
    rev=$(jq -r '.value.vcsRevision' <<<"$entry")

    echo "  [*] Prefetching $name"

    sha=$(nix-prefetch-git \
      --url "$url" \
      --rev "$rev" \
      --fetch-submodules \
      | jq -r '.sha256')

    cat >> "$outfile" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
  };

EOF
  done

  cat >> "$outfile" <<'EOF'
}
EOF

  echo "[✓] Wrote $outfile"
}

# -------------------------
# Main
# -------------------------

# Root deps
nimble lock
generate_deps \
  "nimble.lock" \
  "nix/libp2p-deps.nix"

# C bindings deps
(
  cd cbind
  nimble lock
)
generate_deps \
  "cbind/nimble.lock" \
  "nix/cbind-deps.nix"

