#!/usr/bin/env bash
set -euo pipefail

LOCKFILE="nimble.lock"
DEPS_FILE="nix/deps.nix"
TMP_FETCH_DIR=$(mktemp -d)

mkdir -p nix

if ! command -v jq >/dev/null; then
  echo "error: jq is required"
  exit 1
fi

if ! command -v nix-prefetch-git >/dev/null; then
  echo "error: nix-prefetch-git is required"
  exit 1
fi

if [ ! -f "$LOCKFILE" ]; then
  echo "error: nimble.lock not found (run 'nimble lock')"
  exit 1
fi

echo "[*] Writing Nix deps to $DEPS_FILE"

# Start the Nix file
cat > "$DEPS_FILE" <<EOF
# This file is autogenerated from $LOCKFILE
# Do not edit manually
{ pkgs }:

let
EOF

# Create a directory in the Nix store that will hold all dependencies
cat >> "$DEPS_FILE" <<'EOF'
  fetchedDeps = pkgs.runCommand "nim-deps" {
    nativeBuildInputs = [ pkgs.makeWrapper ];
  } ''
EOF

# Loop through all git packages in nimble.lock
jq -c '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
' "$LOCKFILE" | while read -r entry; do
  name=$(echo "$entry" | jq -r '.key')
  url=$(echo "$entry" | jq -r '.value.url')
  rev=$(echo "$entry" | jq -r '.value.vcsRevision')

  if [ -z "$url" ] || [ -z "$rev" ]; then
    echo "[!] skipping $name (missing url or revision)"
    continue
  fi

  echo "[*] prefetching $name..."
  sha=$(nix-prefetch-git "$url" --rev "$rev" | jq -r '.sha256')

  # Write nix commands to fetch and copy each repo into the common folder
  cat >> "$DEPS_FILE" <<EOF
    src=\${pkgs.fetchgit {
      url = "$url";
      rev = "$rev";
      sha256 = "$sha";
    }}
    mkdir -p \$out/$name
    cp -r \$src/* \$out/$name/
EOF

  echo "[*] Added $name"
done

# Close the runCommand
cat >> "$DEPS_FILE" <<'EOF'
  '';
in
{
  # Expose the single directory with all deps
  fetchedDeps = fetchedDeps;
}
EOF

echo "[✓] deps.nix generated at $DEPS_FILE"
echo "[*] You can now use `fetchedDeps` in your flake.nix or build scripts"

