#!/usr/bin/env bash
set -euo pipefail

LOCKFILE="nimble.lock"
DEPS_FILE="nix/deps.nix"

if ! command -v jq >/dev/null; then
  echo "error: jq is required"
  exit 1
fi

if [ ! -f "$LOCKFILE" ]; then
  echo "error: nimble.lock not found (run 'nimble lock')"
  exit 1
fi

echo "[*] Writing Nix deps to $DEPS_FILE"

cat > "$DEPS_FILE" <<EOF
# This file is autogenerated from $LOCKFILE
# Do not edit manually
{ pkgs }:

{
EOF

jq -c '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
' "$LOCKFILE" | while read -r entry; do

  name=$(echo "$entry" | jq -r '.key')
  url=$(echo "$entry" | jq -r '.value.url')
  rev=$(echo "$entry" | jq -r '.value.vcsRevision')
  sha1=$(echo "$entry" | jq -r '.value.checksums.sha1 // ""')

  if [ -z "$url" ] || [ -z "$rev" ]; then
    echo "[!] skipping $name (missing url or revision)"
    continue
  fi

  echo "  $name = pkgs.fetchgit {" >> "$DEPS_FILE"
  echo "    url = \"$url\";" >> "$DEPS_FILE"
  echo "    rev = \"$rev\";" >> "$DEPS_FILE"
  if [ -n "$sha1" ] && [ "$sha1" != "null" ]; then
    echo "    sha1 = \"$sha1\";" >> "$DEPS_FILE"
  else
    echo "    # TODO: add sha256 with nix-prefetch-git" >> "$DEPS_FILE"
  fi
  echo "  };" >> "$DEPS_FILE"

done

echo "}" >> "$DEPS_FILE"

echo "[✓] deps.nix generated"

