# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright (c) Status Research & Development GmbH

import std/[algorithm, os, sequtils, strutils, tables]
import results, stew/byteutils
import
  ../../../libp2p/[
    crypto/crypto,
    peerid,
    protocols/kademlia/routing_table,
    protocols/kademlia/types,
    protocols/service_discovery/types,
  ]
import ../../tools/crypto

const
  OutputPath = "tests/libp2p/service_discovery/static_bucket_keys.nim"
  BucketsCount = 16
  MaxTriesPerService = 20_000_000
  ServiceNames = ["service"]

proc requiredBucketCounts(): Table[int, int] =
  ## Keep the lookup tests deterministic:
  ## - bucket 0 needs enough keys for same-bucket K_lookup tests
  ## - bucket 1 gives the distinct-bucket tests a higher service bucket
  result[0] = 8
  result[1] = 2

proc nimStringLiteral(s: string): string =
  "\"" & s.replace("\\", "\\\\").replace("\"", "\\\"") & "\""

proc privKeyToInitHex(pk: PrivateKey): string =
  var buf = newSeq[byte](256)
  let n = pk.toBytes(buf).valueOr:
    raiseAssert "toBytes failed while generating static bucket keys"
  byteutils.toHex(buf[0 ..< n])

proc hasEnoughKeys(
    keysByBucket: Table[int, seq[string]], required: Table[int, int]
): bool =
  for bucket, needed in required:
    if keysByBucket.getOrDefault(bucket, @[]).len < needed:
      return false
  true

proc collectKeysForService(
    serviceName: string, required: Table[int, int]
): Table[int, seq[string]] =
  let serviceId = serviceName.hashServiceId()
  var tries = 0

  while tries < MaxTriesPerService and not result.hasEnoughKeys(required):
    let pk = PrivateKey.random(rng()).get()
    let bucket = bucketIndex(
      serviceId,
      PeerId.init(pk).get().toKey(),
      Opt.none(XorDHasher),
      maxBuckets = BucketsCount,
      selfIdPreHashed = true,
    )

    let needed = required.getOrDefault(bucket, 0)
    if needed > 0 and result.getOrDefault(bucket, @[]).len < needed:
      result.mgetOrPut(bucket, @[]).add(privKeyToInitHex(pk))

    inc tries

  if not result.hasEnoughKeys(required):
    raiseAssert "could not synthesize enough static bucket keys for " & serviceName

proc renderStaticBucketKeys(
    keysByService: Table[string, Table[int, seq[string]]]
): string =
  result.add "# SPDX-License-Identifier: Apache-2.0 OR MIT\n"
  result.add "# Copyright (c) Status Research & Development GmbH\n"
  result.add "{.used.}\n\n"
  result.add "import tables\n\n"
  result.add "# Generated by tests/libp2p/service_discovery/generate_bucket_keys.nim.\n"
  result.add "# Regenerate with:\n"
  result.add "#   nim r --verbosity:0 --hints:off tests/libp2p/service_discovery/generate_bucket_keys.nim\n"
  result.add "const serviceBucketLookupTable* = block:\n"
  result.add "  var m = initTable[string, Table[int, seq[string]]]()\n"

  for serviceIdx, serviceName in ServiceNames:
    let keysByBucket = keysByService[serviceName]
    result.add "  var bucketKeys" & $serviceIdx & " = initTable[int, seq[string]]()\n\n"

    for bucket in keysByBucket.keys.toSeq.sorted():
      result.add "  bucketKeys" & $serviceIdx & "[" & $bucket & "] = @[\n"
      for hexKey in keysByBucket[bucket]:
        result.add "    " & nimStringLiteral(hexKey) & ",\n"
      result.add "  ]\n"

    result.add "  m[" & nimStringLiteral(serviceName) & "] = bucketKeys" & $serviceIdx & "\n"

  result.add "  m\n"

when isMainModule:
  let required = requiredBucketCounts()
  var keysByService = initTable[string, Table[int, seq[string]]]()

  for serviceName in ServiceNames:
    keysByService[serviceName] = collectKeysForService(serviceName, required)

  createDir(parentDir(OutputPath))
  writeFile(OutputPath, renderStaticBucketKeys(keysByService))
  echo "wrote ", OutputPath
