#!/usr/bin/env bash
# Nim-LibP2P
# Copyright (c) 2023-2026 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0 ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.
set -euo pipefail

usage() {
  cat <<EOF
Usage:
  $0 <lockfile> <output.nix> [package ...]

Example:
  $0 nimble.lock nix/deps.nix
  $0 cbind/nimble.lock nix/cbind-deps.nix taskpools cbor_serialization ffi
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

LOCKFILE="$1"
OUTFILE="$2"
PACKAGE_FILTER=("${@:3}")

command -v jq >/dev/null || { echo "error: jq required"; exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "error: nix-prefetch-git required"; exit 1; }

if [[ ! -f "$LOCKFILE" ]]; then
  echo "[!] $LOCKFILE not found"
  echo "[*] Generating $LOCKFILE"

  (
    LOCKDIR="$(dirname "$LOCKFILE")"
    cd "$LOCKDIR" || { echo "error: $LOCKDIR does not exist"; exit 1; }
    nimble lock
  )
fi

echo "[*] Generating $OUTFILE from $LOCKFILE"

mkdir -p "$(dirname "$OUTFILE")"

if [[ ${#PACKAGE_FILTER[@]} -gt 0 ]]; then
  PACKAGE_FILTER_JSON=$(printf '%s\n' "${PACKAGE_FILTER[@]}" | jq -R . | jq -s .)
else
  PACKAGE_FILTER_JSON='[]'
fi

cat > "$OUTFILE" <<EOF
# AUTOGENERATED from $LOCKFILE
# Do not edit manually
{ pkgs }:

{
EOF

jq -c --argjson package_filter "$PACKAGE_FILTER_JSON" '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
  | select(($package_filter | length) == 0 or (.key as $name | $package_filter | index($name)))
' "$LOCKFILE" | while read -r entry; do
  name=$(jq -r '.key' <<<"$entry")
  url=$(jq -r '.value.url' <<<"$entry")
  rev=$(jq -r '.value.vcsRevision' <<<"$entry")

  echo "  [*] Prefetching $name"

  sha=$(nix-prefetch-git \
    --url "$url" \
    --rev "$rev" \
    --fetch-submodules \
    | jq -r '.sha256')

  cat >> "$OUTFILE" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
  };

EOF
done

cat >> "$OUTFILE" <<'EOF'
}
EOF

echo "[✓] Wrote $OUTFILE"
