# Nim-LibP2P
# Copyright (c) 2023-2026 Status Research & Development GmbH
# Licensed under either of
#  * Apache License, version 2.0 ([LICENSE-APACHE](LICENSE-APACHE))
#  * MIT license ([LICENSE-MIT](LICENSE-MIT))
# at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.
#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF
Usage:
  $0 <nimble.lock> <output.nix>

Example:
  $0 nimble.lock nix/deps.nix
  $0 cbind/nimble.lock nix/cbind-deps.nix
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

LOCKFILE="$1"
OUTFILE="$2"

command -v jq >/dev/null || { echo "error: jq required"; exit 1; }
command -v nix-prefetch-git >/dev/null || { echo "error: nix-prefetch-git required"; exit 1; }

if [[ ! -f "$LOCKFILE" ]]; then
  echo "error: lockfile not found: $LOCKFILE"
  exit 1
fi

echo "[*] Generating $OUTFILE from $LOCKFILE"

mkdir -p "$(dirname "$OUTFILE")"

cat > "$OUTFILE" <<'EOF'
# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
EOF

jq -c '
  .packages
  | to_entries[]
  | select(.value.downloadMethod == "git")
' "$LOCKFILE" | while read -r entry; do
  name=$(jq -r '.key' <<<"$entry")
  url=$(jq -r '.value.url' <<<"$entry")
  rev=$(jq -r '.value.vcsRevision' <<<"$entry")

  echo "  [*] Prefetching $name"

  sha=$(nix-prefetch-git \
    --url "$url" \
    --rev "$rev" \
    --fetch-submodules \
    | jq -r '.sha256')

  cat >> "$OUTFILE" <<EOF
  ${name} = pkgs.fetchgit {
    url = "${url}";
    rev = "${rev}";
    sha256 = "${sha}";
    fetchSubmodules = true;
  };

EOF
done

cat >> "$OUTFILE" <<'EOF'
}
EOF

echo "[✓] Wrote $OUTFILE"

