name: Daily Nimbus

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile_nimbus:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-daily-ci')
    timeout-minutes: 80
    name: 'Compile Nimbus (linux-amd64)'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Compile nimbus using nim-libp2p
        run: |
          git clone --branch unstable --single-branch https://github.com/status-im/nimbus-eth2.git
          cd nimbus-eth2
          git submodule set-branch --branch ${{ github.sha }} vendor/nim-libp2p

          make -j"$(nproc)"
          make -j"$(nproc)" nimbus_beacon_node
