name: Daily Nimbus

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile_nimbus:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-daily-ci')
    timeout-minutes: 80
    name: 'Compile Nimbus (linux-amd64)'
    runs-on: ubuntu-latest
    steps:
      - name: Compile nimbus using nim-libp2p
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          git clone --branch unstable --single-branch https://github.com/status-im/nimbus-eth2.git
          cd nimbus-eth2
          git submodule update --init --recursive
          cd vendor/nim-libp2p
          git fetch https://github.com/vacp2p/nim-libp2p.git "$GITHUB_SHA"
          git checkout FETCH_HEAD
          cd ../..

          # TODO: Remove this temporary vendor once nimbus-eth2 is updated to include plum.
          git clone https://github.com/logos-storage/nim-libplum.git vendor/nim-libplum
          git -C vendor/nim-libplum checkout acefbe424cf9d1f05f2d93533790c9ac4e034df8
          git -C vendor/nim-libplum submodule update --init --recursive

          make -j"$(nproc)" nimbus_beacon_node
