name: Daily test all (latest dependencies)

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  test_latest_deps:
    name: Daily test all (latest dependencies)
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-daily-ci')
    uses: ./.github/workflows/daily_test_all_latest_deps_matrix.yml
