name: Daily i386

on:
  schedule:
    - cron: "31 6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_i386_latest:
    name: Daily i386 (latest dependencies)
    uses: ./.github/workflows/daily_common.yml
    with:
      nim: "[
          {'ref': 'v2.0.16', 'memory_management': 'refc'},
          {'ref': 'v2.2.6', 'memory_management': 'refc'},
          {'ref': 'devel', 'memory_management': 'refc'},
        ]"
      configuration: "[
          {'os': 'linux', 'cpu': 'i386', 'cc': 'gcc', 'builder': 'ubuntu-22.04', 'shell': 'bash'},
        ]"
  test_i386_pinned:
    name: Daily i386 (pinned dependencies)
    uses: ./.github/workflows/daily_common.yml
    with:
      pinned_deps: true
      nim: "[
          {'ref': 'v2.0.16', 'memory_management': 'refc'},
          {'ref': 'v2.2.6', 'memory_management': 'refc'},
          {'ref': 'devel', 'memory_management': 'refc'},
        ]"
      configuration: "[
          {'os': 'linux', 'cpu': 'i386', 'cc': 'gcc', 'builder': 'ubuntu-22.04', 'shell': 'bash'},
        ]"
