name: Daily without feature flags

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-no-flags:
    env:
      NIMBLE_COMMIT: aa8e6ea09ecac774b6fad42552569ce07bef37ec # v0.24.1
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-daily-ci')
    timeout-minutes: 55
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    name: "Build and run"
    runs-on: macos-15 # using macos-15 as it is fastests to compile and run
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          shell: bash
          os: macos-15
          cpu: arm64
          nim_ref: v2.2.10

      - name: Restore dependencies from cache
        uses: "./.github/actions/install_test_deps"
        with:
          os: macos-15
          cpu: arm64
          cc: clang
          nim_ref: v2.2.10

      - name: Setup deps
        run: make setup
        
      - name: Build without feature flags
        run: |
          nim c --mm:refc --cc:clang ./tests/test_all

      - name: Run tests
        run: |
          ./tests/test_all
