name: Daily Tests
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  test_amd64:
    name: Daily amd64
    uses: ./.github/workflows/base_tests.yml
    with:
      include: "[{'nim-branch': 'version-2-0'}]"
      exclude: "[{'platform': {'cpu': 'i386'}}]"

  test_i386:
    name: Daily i386
    uses: ./.github/workflows/base_tests.yml
    with:
      exclude: "[{'platform': {'cpu': 'amd64'}}]"

  test_nim_devel:
    name: Daily 
    uses: ./.github/workflows/base_tests.yml
    with:
      include: "[{'nim-branch': 'devel'}]"
      exclude: "[{'platform': {'os': 'windows'}}, {'platform': {'os': 'macos'}}, {'platform': {'cpu': 'i386'}}]"
