name: Daily amd64

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_amd64_latest:
    name: Daily test amd64 (latest dependencies)
    uses: ./.github/workflows/daily_common.yml
    with:
      allow_failure: ${{ github.event_name == 'schedule' }}
      allow_devel_failure: ${{ github.event_name == 'schedule' }}
      nim: "[
          {'ref': 'v2.0.16', 'memory_management': 'refc'},
          {'ref': 'v2.2.6', 'memory_management': 'refc'},
          {'ref': 'devel', 'memory_management': 'refc'},
        ]"
      configuration: "[
          {'os': 'linux', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'ubuntu-22.04', 'shell': 'bash'},
          {'os': 'linux-gcc-14', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'ubuntu-24.04', 'shell': 'bash'},
          {'os': 'windows', 'cpu': 'amd64', 'cc': 'clang', 'builder': 'windows-2022', 'shell': 'bash'},
          {'os': 'windows', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'windows-2022', 'shell': 'msys2 {0}'},
        ]"
  test_amd64_pinned:
    name: Daily test amd64 (pinned dependencies)
    uses: ./.github/workflows/daily_common.yml
    with:
      pinned_deps: true
      allow_devel_failure: ${{ github.event_name == 'schedule' }}
      nim: "[
          {'ref': 'v2.0.16', 'memory_management': 'refc'},
          {'ref': 'v2.2.6', 'memory_management': 'refc'},
          {'ref': 'devel', 'memory_management': 'refc'},
        ]"
      configuration: "[
          {'os': 'linux', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'ubuntu-22.04', 'shell': 'bash'},
          {'os': 'linux-gcc-14', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'ubuntu-24.04', 'shell': 'bash'},
          {'os': 'windows', 'cpu': 'amd64', 'cc': 'clang', 'builder': 'windows-2022', 'shell': 'bash'},
          {'os': 'windows', 'cpu': 'amd64', 'cc': 'gcc', 'builder': 'windows-2022', 'shell': 'msys2 {0}'},
        ]"
  notify-on-failure:
    name: Notify Discord on Failure
    needs: [test_amd64_latest, test_amd64_pinned]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Discord notification
        uses: ./.github/actions/discord_notify
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
