name: Examples

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    timeout-minutes: 30
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    name: "Build Examples"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          shell: bash
          os: linux
          cpu: amd64
          nim_ref: version-1-6

      - name: Restore deps from cache
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: nimbledeps
          key: nimbledeps-${{ hashFiles('.pinned') }}

      - name: Install deps
        if: ${{ steps.deps-cache.outputs.cache-hit != 'true' }}
        run: |
          nimble install_pinned

      - name: Build and run examples
        run: |
          nim --version
          nimble --version
          gcc --version

          NIMFLAGS="${NIMFLAGS} --mm:${{ matrix.nim.memory_management }}"
          nimble examples
