name: Examples

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    env:
      NIMBLE_COMMIT: aa8e6ea09ecac774b6fad42552569ce07bef37ec # v0.24.1
    timeout-minutes: 30
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    name: "Build Examples"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          shell: bash
          os: linux
          cpu: amd64
          nim_ref: v2.2.10

      - name: Restore dependencies from cache
        uses: "./.github/actions/install_root_deps"
        with:
          os: linux
          cpu: amd64
          cc: gcc
          nim_ref: v2.2.10

      - name: Setup deps
        run: make nimble.paths
        
      - name: Build and run examples
        run: |
          nim --version
          nimble --version
          gcc --version
          cd examples && nimble examples
