name: Linters

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nph:
    name: NPH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # In PR, has extra merge commit: ^1 = PR, ^2 = base

      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.6.1
          options: "examples libp2p tests tools *.nim*"
          fail: true
          suggest: true
