name: Daily
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1

  build:
    needs: delete-cache
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
          - os: linux
            cpu: i386
          - os: macos
            cpu: amd64
          - os: windows
            cpu: amd64
          #- os: windows
            #cpu: i386
        branch: [version-1-6, version-2-0, devel]
        include:
          - target:
              os: linux
            builder: ubuntu-20.04
            shell: bash
          - target:
              os: macos
            builder: macos-12
            shell: bash
          - target:
              os: windows
            builder: windows-2019
            shell: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    continue-on-error: ${{ matrix.branch == 'devel' || matrix.branch == 'version-2-0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: ${{ matrix.target.os }}
          shell: ${{ matrix.shell }}
          nim_branch: ${{ matrix.branch }}
          cpu: ${{ matrix.target.cpu }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.15.5'

      - name: Install p2pd
        run: |
          V=1 bash scripts/build_p2pd.sh p2pdCache 124530a3

      - name: Run tests
        run: |
          nim --version
          nimble --version
          nimble install -y --depsOnly
          NIMFLAGS="${NIMFLAGS} --gc:refc" nimble test
          if [[ "${{ matrix.branch }}" == "devel" ]]; then
            echo -e "\nTesting with '--gc:orc':\n"
            NIMFLAGS="${NIMFLAGS} --gc:orc" nimble test
          fi
