name: Legacy Platforms
on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  call-multi-nim-common:
    uses: status-im/nim-libp2p/.github/workflows/multi_nim_common.yml@unstable
    with:
      nim-branch: "['version-1-6','version-2-0']"
      platform: "[{'os':'linux','cpu':'i386'}]"


