name: Daily Nim Devel
on:
#  schedule:
#    - cron: "30 6 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  call-multi-nim-common:
    uses: status-im/nim-libp2p/.github/workflows/multi_nim_common.yml@simplifly-ci-matrix
    with:
      nim-branch: 'devel'
      cpu: 'amd64'
      exclude: ''
