name: Daily i386
on:
#  schedule:
#    - cron: "30 6 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  call-multi-nim-common:
    uses: status-im/nim-libp2p/.github/workflows/multi_nim_common.yml@unstable
    with:
      nim-branch: "['version-1-6','version-2-0', 'devel']"
      cpu: "['i386']"
      exclude:
        - os: macos
