name: Linux amd64 Test (v2.2.10 refc)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 55
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: linux
          cpu: amd64
          shell: bash
          nim_ref: v2.2.10

      - name: Restore dependencies from cache
        id: deps-cache
        uses: actions/cache@v5
        with:
          path: nimbledeps
          key: nimbledeps-linux-amd64-gcc-${{ hashFiles('.pinned') }}

      - name: Install deps
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          nimble install_pinned

      - name: Build prerequisites
        run: make nimble.paths nat_libs

      - name: Restore build cache
        uses: actions/cache@v5
        with:
          path: nimcache
          key: ${{ github.ref_name }}-nimcache-test_all-linux-amd64-gcc-refc-${{ hashFiles('tests/*.nim', 'libp2p/**/*.nim') }}
          restore-keys: |
            nimcache-test_all-linux-amd64-gcc-refc-

      - name: Build test_all
        id: build-test-all
        run: |
          nim c \
            --nimcache:nimcache/test_all \
            --mm:refc \
            --opt:speed \
            --styleCheck:usages \
            --styleCheck:error \
            --parallelBuild:0 \
            --threads:on \
            --skipUserCfg \
            ./tests/test_all

      - name: Run tests
        id: run-tests
        run: |
          ./tests/test_all --output-level=VERBOSE --console --xml:tests/results_test_all.xml

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() && steps.run-tests.outcome == 'failure' }}
        with:
          name: Test Report
          path: tests/results_*.xml
          reporter: jest-junit
          list-suites: 'failed'
          list-tests: 'failed'
          fail-on-error: 'false'
